using UnityEngine;
using System.Collections.Generic;
using CW.Common;

namespace SpaceGraphicsToolkit
{
	/// <summary>This component is automatically generated by SGT components that implement GameObject pooling (e.g. SgtTerrainFace).</summary>
	[ExecuteInEditMode]
	[AddComponentMenu("")]
	public class SgtPoolComponent : MonoBehaviour
	{
		/// <summary>The name of the type this pool manages.</summary>
		public string TypeName;

		/// <summary>The pooled elements in this pool.</summary>
		public List<Component> Elements = new List<Component>();

		/// <summary>This stores all active and enabled instances of this component.</summary>
		public static LinkedList<SgtPoolComponent> Instances = new LinkedList<SgtPoolComponent>(); private LinkedListNode<SgtPoolComponent> node;

		protected virtual void OnDestroy()
		{
			for (var i = Elements.Count - 1; i >= 0; i--)
			{
				var element = Elements[i];

				if (element != null)
				{
					DestroyImmediate(element.gameObject);
				}
			}
		}

		protected virtual void OnEnable()
		{
			node = Instances.AddLast(this);
		}

		protected virtual void OnDisable()
		{
			Instances.Remove(node); node = null;
		}

#if UNITY_EDITOR
		protected virtual void Update()
		{
			// Auto destroy this pool if it exists in edit mode
			if (Application.isPlaying == false)
			{
				CwHelper.Destroy(gameObject);
			}
		}
#endif

#if UNITY_EDITOR
		protected virtual void OnDrawGizmos()
		{
			// Auto destroy this pool if it exists in edit mode
			if (Application.isPlaying == false)
			{
				CwHelper.Destroy(gameObject);
			}
		}
#endif
	}

	public static class SgtComponentPool<T>
		where T : Component
	{
		// The pool component for this static class
		private static SgtPoolComponent pool;

		// The amount of pooled objects
		public static int Count
		{
			get
			{
				UpdateComponent(false);

				if (pool != null)
				{
					return pool.Elements.Count;
				}

				return 0;
			}
		}

		public static T Add(T entry)
		{
			return Add(entry, null);
		}

		public static T Add(T element, System.Action<T> onAdd)
		{
			if (element != null)
			{
				if (onAdd != null)
				{
					onAdd(element);
				}

				UpdateComponent(true);
#if UNITY_EDITOR
				element.gameObject.hideFlags = HideFlags.DontSave;
#endif
				element.transform.SetParent(pool.transform, false);

				element.gameObject.SetActive(false);

				pool.Elements.Add(element);
			}

			return null;
		}

		public static void Cache()
		{
			UpdateComponent(true);

			var gameObject = new GameObject();
#if UNITY_EDITOR
			gameObject.hideFlags = HideFlags.DontSave;
#endif
			gameObject.transform.SetParent(pool.transform, false);

			gameObject.SetActive(false);

			var element = gameObject.AddComponent<T>();

			pool.Elements.Add(element);
		}
	
		public static T Pop(Transform parent, string name, int layer)
		{
			var element = Pop();

			if (element != null)
			{
				element.name = name;

				element.transform.SetParent(parent, false);

				element.gameObject.layer = layer;
			}
			else
			{
				var gameObject = new GameObject(name);

				gameObject.layer = layer;

				gameObject.transform.SetParent(parent, false);

				element = gameObject.AddComponent<T>();
			}

			return element;
		}

		public static T Pop()
		{
			return Pop(null);
		}

		public static T Pop(System.Predicate<T> match)
		{
			UpdateComponent(false);

			if (pool != null)
			{
				var elements = pool.Elements;
				var index    = elements.Count - 1;

				if (match != null)
				{
					for (var i = index; i >= 0; i--)
					{
						var element = elements[i];

						if (match((T)element) == true)
						{
							index = i; break;
						}
					}
				}

				if (index >= 0)
				{
					var element = (T)elements[index];

					elements.RemoveAt(index);

					if (element != null)
					{
#if UNITY_EDITOR
						element.gameObject.hideFlags = HideFlags.None;
#endif
						element.gameObject.SetActive(true);
					}

					return element;
				}
			}

			return null;
		}

		private static void UpdateComponent(bool allowCreation)
		{
			if (pool == null)
			{
				var typeName = typeof(T).Name;

				foreach (var findPool in SgtPoolComponent.Instances)
				{
					if (findPool.TypeName == typeName)
					{
						pool = findPool; return;
					}
				}

				if (allowCreation == true)
				{
					pool = new GameObject("SgtPoolComponent<" + typeName + ">").AddComponent<SgtPoolComponent>();

					pool.TypeName = typeName;

					if (Application.isPlaying == true)
					{
						Object.DontDestroyOnLoad(pool);
					}
#if UNITY_EDITOR
					pool.gameObject.hideFlags = HideFlags.DontSave;
#endif
				}
			}
		}
	}
}

#if UNITY_EDITOR
namespace SpaceGraphicsToolkit
{
	using UnityEditor;
	using TARGET = SgtPoolComponent;

	[CanEditMultipleObjects]
	[CustomEditor(typeof(TARGET))]
	public class SgtPoolComponent_Editor : CwEditor
	{
		protected override void OnInspector()
		{
			TARGET tgt; TARGET[] tgts; GetTargets(out tgt, out tgts);

			BeginDisabled();
				Draw("TypeName", "The name of the type this pool manages.");
				Draw("Elements", "The pooled elements in this pool.");
			EndDisabled();
			Info("SgtPoolComponent are not saved to your scene, so don't worry if you see it in edit mode.");
		}
	}
}
#endif